### PR TITLE
Display buttons in a button group #141

### PR DESCRIPTION
**Pull request by Divyateja04**
As requested in the issue: Display buttons in a button group #141
This has been done

### CODE REVIEW

**Comment by programarivm** [comment]
Thanks for the PR,

Looks good but it seems as if the **Offer draw** button is missing for some reason.

At the present moment, possibly a simple solution would consist in one file.

```
import React from 'react';
import Button from '@material-ui/core/Button';
import { useSelector, useDispatch } from 'react-redux';
import requestTakebackDialogActionTypes from '../constants/requestTakebackDialogActionTypes';

const ButtonsPlayFriendMode = () => {
  const state = useSelector(state => state);
  const dispatch = useDispatch();

  const [anchorElRequestTakeback, setAnchorElRequestTakeback] = React.useState(null);

  const handleCloseRequestTakeback = () => {
    setAnchorElRequestTakeback(null);
  };

  if (state.mode.playfriend.accepted) {
    return (
      <div>
        <Button
        variant="outlined"
        onClick={() => {
          dispatch({ type: requestTakebackDialogActionTypes.OPEN });
          handleCloseRequestTakeback();
        }}
        >
          Propose a takeback
        </Button>
        <Button variant="outlined">Resign</Button>
        <Button variant="outlined">Offer draw</Button>
      </div>
    );
  }

  return null;
}

export default ButtonsPlayFriendMode;
```

Keep it up, and happy learning and coding.

**Comment by Divyateja04** [comment]
But in my code its already there right?
You checked that?

**Comment by programarivm** [comment]
Sorry but still getting this error if I'm not very much mistaken:

```
Failed to compile
./node_modules/@chesslablab/redux-chess/dist/components/Chess.js
Module not found: Can't resolve './ButtonsResignGame.js' in '/home/standard/projects/testing-redux-chess/node_modules/@chesslablab/redux-chess/dist/components'
```

I'm running this command:

```
npm run publish:npm --prefix /home/standard/projects/@chesslablab/redux-chess && npm run update:local:redux-chess && npm start
```

It looks like something got out of sync. Did you git pull from master before committing in order to keep your branch up to date with the latest code?

Thanks!

**Comment by Divyateja04** [comment]
Sorry I understood the mistake, I'll fix it and PR again...

**Comment by Divyateja04** [comment]
image
This looks good?
Should I add any padding between the buttons though?

**Comment by programarivm** [comment]
That's okay, no worries I messed up something today lol https://github.com/chesslablab/php-chess/pull/61

Let's review this one within the next few hours, have a nice day!

**Comment by Divyateja04** [comment]
Yeah I mean, everybody makes mistakes....that's one really good advantage about open-sourcing and stuff
The more mistakes we make, the more better we become in that field

That's supposed to be a short but nice piece to motivate you
Hope it helps!

**Comment by programarivm** [comment]
Thanks for the updates.

The PR looks good, let me just point out two things:

1. It'd be great if the buttons could be resized to a small size and the text displayed in lowercase
2. It seems as if the recently merged drag-and-drop and FEN functionalities are missing in the PR. 

May I ask you to `git pull master` before sending the PR so that your branch is up to date with the latest code?

I can't wait to see what you come up with! 

Happy learning and coding.

**Comment by Divyateja04** [comment]
Can you check if the 2 was solved?

**Comment by Divyateja04** [comment]
I think both should have been solved...can you check?

**Comment by programarivm** [comment]
Thanks for the updates.

Both have been solved; however at the present moment the button group seems to be missing in **Play with a friend** mode.

**Comment by Divyateja04** [comment]
ahh sorry, I remove that for testing(makes it easier)...but sent the updated PR

**Comment by programarivm** [comment]
Thanks for the updates!

**Pull request merged**
