### PR TITLE
#264 renamed opening search dialogs

### PR DESCRIPTION
**Pull request by Amit91848**
Renamed the opening search dialog files in `src/components/dialogs` as well as `chess.js`

### CODE REVIEW

**Comment by programarivm** [comment]
@Amit91848 thanks for contributing to this repo.

Sorry that I felt free to commit a few changes to your PR too and created a new PR with my branch as per [GitHub Docs](https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally). Possibly for this reason this contribution is not listed on the **Contributors** section at [the repo page](https://github.com/chesslablab/redux-chess).

Please let me know if you'd want to comment on any of the following issues — Happy learning and coding!

- https://github.com/chesslablab/redux-chess/issues/235
- https://github.com/chesslablab/redux-chess/issues/239
- https://github.com/chesslablab/redux-chess/issues/240
- https://github.com/chesslablab/redux-chess/issues/262

Sorry about that, next time let's engage in a review instead to merge your PR instead of mine.

Keep it up, and happy learning and coding!

**Comment by Amit91848** [comment]
Sorry I am new to open source so things are still a bit confusing. I would like to contribute more. It would be great if you would guide me through the process.

**Comment by programarivm** [comment]
Thank you! We're all here to learn, please let me know if you'd want to solve this issue:

- https://github.com/chesslablab/redux-chess/issues/240

This one is intended to install and set up the [`testing-redux-chess`](https://github.com/chesslablab/testing-redux-chess) app.

Keep it up, and happy coding.

**Comment by Amit91848** [comment]
Yeah sure I would love to work on it. What exactly should I do?

**Comment by programarivm** [comment]
Just comment on the issue you'd want to be assigned to: Happy learning and coding!

**Pull request merged**
